# The Digit Dataset:-

This dataset is made up of 1797  8x8. Each image like the one shown below, is of a hand written digit. in order to utilize an 8x8 figure like this, we'd have to first transform it into a feature vector with length 64.

# Digits Recognition..

In [6]:
from sklearn.datasets import load_digits

In [7]:
digits=load_digits()

In [8]:
digits.keys()

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

In [9]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
digits.images

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

In [35]:
x=digits.data

In [36]:
x.shape

(1797, 64)

In [37]:
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [39]:
print(digits.data[0].shape)
digits.images[0].shape

(64,)


(8, 8)

In [40]:
y=digits.target

In [41]:
y.shape

(1797,)

In [42]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=2,random_state=10)

In [45]:
x_train.shape

(1795, 64)

In [46]:
x_test.shape

(2, 64)

In [47]:
y_train.shape

(1795,)

In [48]:
y_test.shape

(2,)

In [49]:
import numpy as np

In [51]:
print(np.unique(y_test))
np.bincount(y_test)

[2 5]


array([0, 0, 1, 0, 0, 1], dtype=int64)

In [52]:
from sklearn.neighbors import KNeighborsClassifier

In [53]:
knn= KNeighborsClassifier(metric='euclidean')

In [54]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [55]:
pred=knn.predict(x_test)

In [56]:
pred[0]

5

In [57]:
y_test[0]

5

In [58]:
x_test[0]

array([ 0.,  0.,  8., 14., 16., 16.,  1.,  0.,  0.,  6., 16., 16.,  8.,
        3.,  0.,  0.,  0., 14., 14.,  1.,  0.,  0.,  0.,  0.,  0., 10.,
       15.,  4.,  0.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,
        0.,  0.,  0.,  1.,  8., 15.,  2.,  0.,  0.,  0.,  0.,  2., 13.,
       15.,  0.,  0.,  0.,  0.,  0., 10., 16.,  4.,  0.,  0.,  0.])

In [59]:
pred[8]

IndexError: index 8 is out of bounds for axis 0 with size 2

In [60]:
y_test[8]

IndexError: index 8 is out of bounds for axis 0 with size 2

In [61]:
x_test[8]

IndexError: index 8 is out of bounds for axis 0 with size 2

In [62]:
import matplotlib.pyplot as plt

In [63]:
plt.imshow(x_test[8].reshape(8,8),cmap='gray')
#plt.imshow(digits.image[8],cmap='gray')
plt.show()

IndexError: index 8 is out of bounds for axis 0 with size 2

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test,pred)

In [ ]:
np.where(y_test!=pred)

In [66]:
y_test[58]

IndexError: index 58 is out of bounds for axis 0 with size 2

In [67]:
pred[58]

IndexError: index 58 is out of bounds for axis 0 with size 2

In [68]:
y_test[129]

IndexError: index 129 is out of bounds for axis 0 with size 2

In [69]:
pred[129]

IndexError: index 129 is out of bounds for axis 0 with size 2