# IRIS  DATABASE

# goal

* Design a model that is able to automatically recognize IRIS species

# 1.collect data:-

In [1]:
from sklearn.datasets import load_iris
iris=load_iris()

In [2]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

# Features:-

In [3]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
#target name we want to predict
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [7]:
#no of samples and features
n_samples,features= iris.data.shape
print(n_samples,features)

150 4


In [8]:
import numpy as np

In [9]:
#np.unique(iris.target)
np.bincount(iris.target) #find out each class total samples...

array([50, 50, 50], dtype=int64)

In [10]:
x=iris.data #stores all input data in x varible
x.shape

(150, 4)

In [11]:
x.ndim

2

# Target

In [12]:
y=iris.target #stores all output data in y variable
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
y.ndim

1

In [14]:
#how to shuffle both input and output data & split data manually

In [15]:
import pandas as pd

In [16]:
#df=pd.DataFrame(iris.data,columns=iris.feature_names)
df=pd.DataFrame(x,columns=iris.feature_names)
df.loc[:10,:]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
5                 5.4               3.9                1.7               0.4
6                 4.6               3.4                1.4               0.3
7                 5.0               3.4                1.5               0.2
8                 4.4               2.9                1.4               0.2
9                 4.9               3.1                1.5               0.1
10                5.4               3.7                1.5               0.2

In [17]:
#df['target']=iris.target
df['target']=y

In [18]:
df.head

<bound method NDFrame.head of      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
6                  4.6               3.4                1.4               0.3   
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
9                  4.9               3.1                1.5               0.1   
10                 5.4               3.7                1.5               0.2  

In [19]:
data=df.values
data

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [20]:
data.shape

(150, 5)

In [21]:
#shuffle both data input & output
import numpy as np
np.random.shuffle(data)

In [22]:
data[0:20]

array([[5.6, 2.8, 4.9, 2. , 2. ],
       [5.7, 2.8, 4.1, 1.3, 1. ],
       [5.5, 3.5, 1.3, 0.2, 0. ],
       [5.8, 2.7, 5.1, 1.9, 2. ],
       [6.6, 3. , 4.4, 1.4, 1. ],
       [4.8, 3.1, 1.6, 0.2, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5.5, 2.4, 3.7, 1. , 1. ],
       [5.1, 3.8, 1.6, 0.2, 0. ],
       [6.7, 3.1, 4.7, 1.5, 1. ],
       [6.8, 2.8, 4.8, 1.4, 1. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [6.5, 3. , 5.8, 2.2, 2. ],
       [6.7, 2.5, 5.8, 1.8, 2. ],
       [4.9, 2.5, 4.5, 1.7, 2. ],
       [6.3, 3.3, 4.7, 1.6, 1. ],
       [5. , 2.3, 3.3, 1. , 1. ]])

In [23]:
#after shuffle data,split data : 120 samples given for traning & 30 samples given for testing

In [24]:
x_train,y_train=data[:120,:-1],data[:120,-1]

In [25]:
x_test,y_test=data[120:,:-1],data[120:,-1]

In [26]:
x_train.shape

(120, 4)

In [27]:
x_test.shape

(30, 4)

In [28]:
y_train.shape

(120,)

In [29]:
y_test.shape

(30,)

# split data into training and testing data using ML.

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=30,random_state=10)

In [31]:
x_train.shape

(120, 4)

In [32]:
x_test.shape

(30, 4)

about random_state

* after using random_state our split will be always the same. it doesn't matters what the actual random_state number is 42,0,21
* the important thing is that everytime we use 42,we will always get the same output when the first time we make the split.

# 2.import model [choose algos / classifier / estimator]

In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [34]:
#create object of knn classifier

In [35]:
knn=KNeighborsClassifier()

# 3.Train model with training data

In [36]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

# 4. Making prediction on unseen data or testing data

In [37]:
pred=knn.predict(x_test)

In [38]:
pred

array([1, 2, 0, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2])

In [39]:
pred[0]

1

In [40]:
y_test[0]

1

In [41]:
pred[1]

2

In [42]:
y_test[1]

2

# 5.Evaluation

In [43]:
from sklearn.metrics import accuracy_score

In [44]:
accuracy_score(y_test,pred)

0.9666666666666667

In [45]:
knn.score(x_test,y_test)

0.9666666666666667

In [46]:
#find accuracy
print('training accuracy:',knn.score(x_train,y_train))
print('testing accuracy:',knn.score(x_test,y_test))

training accuracy: 0.975
testing accuracy: 0.9666666666666667


# 6.how to find misclassified samples

In [47]:
np.where(pred!=y_test)

(array([6], dtype=int64),)

In [48]:
pred[6]

2

In [49]:
y_test[6]

1

In [50]:
# Evauation results is class 0 & class 2,
#prediction is correct & class 1 prediction is 4% wrong.